"""RabbitMQ configuration"""

RABBITMQ_SERVER = "127.0.0.1"
RABBITMQ_USER = "guest"
RABBITMQ_PASSWORD = "guest"
RABBITMQ_VHOST = "/"
RABBITMQ_EXCHANGE = ""
RABBITMQ_QUEUE = "sample6"
RABBITMQ_EXCHANGE_TYPE = 'direct'
RABBITMQ_DURABLE = True
RABBITMQ_PREFETCH_COUNT = 1
RABBITMQ_DELIVERY_MODE = 2
RABBITMQ_TIMEOUT = 300
